# Set the version of docker compose to use
version: '3.8'

# The containers that compose the project
services:
  db:
    image: postgres:13
    restart: always
    container_name: Betty-organic-db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: organic
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://prisma:prisma@db:5432/organic"
    volumes:
      - .:/app
    command: [ "sh", "entrypoint.sh" ]

volumes:
  postgres_data:
