name: "🐛 Bug Report"
description: Report a bug in the authentication system
title: "[Bug]: "
labels: ["bug", "authentication"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the auth system is affected?
      options:
        - Login
        - Signup
        - Password Reset
        - Email Verification
        - Session Management
        - Role-Based Access
        - Profile Management
        - Database/Migrations
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How do you trigger this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the app are you running?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What browser/node version/etc are you using?
      value: |
        - Node Version:
        - Browser:
        - OS:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: I have searched for similar issues before creating this one
          required: true
