name: "📚 Documentation Update"
description: Suggest improvements to the authentication documentation
title: "[Docs]: "
labels: ["documentation", "authentication"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our authentication documentation!
        Please provide as much detail as possible about what needs to be updated.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs updating?
      options:
        - Setup Guide
        - API Reference
        - Code Examples
        - Architecture Overview
        - Security Guidelines
        - Contributing Guidelines
        - Testing Guide
        - Troubleshooting Guide
    validations:
      required: true

  - type: input
    id: file-link
    attributes:
      label: Documentation File
      description: Which documentation file needs to be updated?
      placeholder: e.g., docs/auth-guide.md
    validations:
      required: true

  - type: dropdown
    id: update-type
    attributes:
      label: Update Type
      description: What kind of update is needed?
      options:
        - Fix Error/Typo
        - Add Missing Information
        - Clarify Existing Content
        - Update Outdated Information
        - Improve Examples
        - Add New Section
        - Reorganize Structure
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: What does the current documentation say?
      placeholder: Copy the relevant section that needs updating...

  - type: textarea
    id: suggested-changes
    attributes:
      label: Suggested Changes
      description: What changes would you like to see?
      placeholder: Describe your proposed changes in detail...
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: Justification
      description: Why are these changes needed?
      placeholder: Explain why these changes would improve the documentation...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples if applicable
      placeholder: Code snippets, screenshots, or use cases that illustrate the need for these changes...

  - type: checkboxes
    id: validations
    attributes:
      label: Documentation Checklist
      description: Please confirm the following
      options:
        - label: I have checked that this isn't already documented elsewhere
          required: true
        - label: These changes are accurate and up-to-date
          required: true
        - label: I am willing to help implement these changes
          required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other context about the documentation update
      placeholder: Add any other relevant information here...
